//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.04 at 10:45:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://simplenlg.googlecode.com/svn/trunk/res/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package simplenlg.xmlrealiser.wrapper;
